### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Grav\Common\Data\Data::merge() must be of the type array...

### ISSUE THREAD

**Issue by bperry11** [getgrav/grav-plugin-simplesearch#162]
Upon installing simplesearch I get this error with each subsequent command to install or update plugins. Removing user/plugins/simplesearch gets rid of error and I am able to install/update other plugins without any problems. 

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Grav\Common\Data\Data::merge() must be of the type array, string given, called in /var/www/public/system/src/Grav/Common/Plugins.php on line 173 and defined in /var/www/public/system/src/Grav/Common/Data/Data.php:163
Stack trace:
#0 /var/www/public/system/src/Grav/Common/Plugins.php(173): Grav\Common\Data\Data->merge('enabled')
#1 /var/www/public/system/src/Grav/Common/Plugins.php(140): Grav\Common\Plugins::get('simplesearch')
#2 /var/www/public/system/src/Grav/Common/GPM/Local/Plugins.php(27): Grav\Common\Plugins::all()
#3 /var/www/public/system/src/Grav/Common/GPM/Local/Packages.php(18): Grav\Common\GPM\Local\Plugins->__construct()
#4 /var/www/public/system/src/Grav/Common/GPM/GPM.php(56): Grav\Common\GPM\Local\Packages->__construct()
#5 /var/www/public/system/src/Grav/Console/Gpm/UpdateCommand.php(134): Grav\Common\GPM\GPM->__construct(false)
#6 /var/www/public/system/src/Grav/Console/ConsoleCommand.php(29): Grav\Console\Gpm\UpdateCommand->serve()
#7 /var/www/public in /var/www/public/system/src/Grav/Common/Data/Data.php on line 163

```

**Comment by bperry11** [comment]
This only happens to me when using the bin/gpm. Manual install worked fine
